### PR TITLE
Ft/create post

### LINKED ISSUE #41: Create a Post
As an author, I would like to be able to create Posts so I can share my thoughts with the world.

**Given** a user is in the app  
**When** they select the `New Post` menu option
**Then** they should be directed to a page with a form for creating a new post

**Given** the user has entered the relevant information for a Post
**When** they click the `Save` button  
**Then** the Post should be saved to the database  
**And** the creation datetime should be automatically set to the current date and time  
**And** the post should automatically be approved  
**And** the user should be recorded as the author of the Post  
**And** the user should be redirected to the new Post's details page

The "relevant information" for a Post is

* Title
* Content
* Category
* Header Image URL (optional)
* Publication Date (optional)

### PR DESCRIPTION
**Pull request by Lincoln-WIlcox**
Added the ability to create new posts.

Added button to navbar to navigate to create post page.
Created post form, which holds all the inputs for a post.
Created create post page, which creates a post on submitting the post form.
Added endpoint for posting post for this user (automatically gets id for the user profile of the logged in user).

closes #41

### CODE REVIEW

**Review by LucasBress0n — APPROVED** [review]
Tested as an Admin, & User. Works as intended.

Uhh the only thing I can see wrong is the CreatPost.jsx, Should be CreatePost.jsx

**Comment by Lincoln-WIlcox** [comment]
> Tested as an Admin, & User. Works as intended.
> 
> Uhh the only thing I can see wrong is the CreatPost.jsx, Should be CreatePost.jsx

resolved

**Review by rubygkendrick — CHANGES_REQUESTED** [review]
all users need access to the categories list for making a new post

**Comment by Lincoln-WIlcox** [comment]
> all users need access to the categories list for making a new post

It seems main now has the authorize annotation removed from the `GetAllCategories` endpoint. This resolves the change request, but introduces a new issue of the endpoint not requiring authorization. I created a new pr to fix this #66

**Review by LucasBress0n — APPROVED** [review]
I've already reviewed this 10/10

**Pull request merged**
